### ISSUE TITLE
ReferenceError: getLightBulbMaxVolCharacteristic is not defined

### ISSUE THREAD

**Issue by ElreboCM** [rogerp67/homebridge-yamaha_mc2#1]
Hi! 
I tested the new plugin immediately. Unfortunately there seems to be a problem:

getLightBulbMaxVolCharacteristic(); // sets maxvol variabele dynamically by asking Yamaha device
/usr/local/lib/node_modules/homebridge-yamaha_mc2/index.js:24
    at Function.Module._load (module.js:493:3)
    at tryModuleLoad (module.js:501:12)
    at Module.load (module.js:561:32)
    at Object.Module._extensions..js (module.js:660:10)
    at Module._compile (module.js:649:30)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:87:38)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:297:29)
    at new Yamaha_mcAccessory (/usr/local/lib/node_modules/homebridge-yamaha_mc2/index.js:24:3)
ReferenceError: getLightBulbMaxVolCharacteristic is not defined
  ^
  getLightBulbMaxVolCharacteristic(); // sets maxvol variabele dynamically by asking Yamaha device
/usr/local/lib/node_modules/homebridge-yamaha_mc2/index.js:24
Mon, 19 Nov 2018 17:06:47 GMT EventedHTTPServer [::ffff:192.168.11.102] HTTP Response is finished

**Comment by rogerp67** [comment]
This was a wrong file, I tried to get the maxVol value automatically but messed up the file. The current version is working (with the static maxVol value in the config.json)
Enjoy!
